"""initial schema

Revision ID: ea20c9e60b83
Revises: 
Create Date: 2026-05-16 19:50:42.362534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea20c9e60b83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('statement', 'credit_card', name='file_type'), nullable=False),
    sa.Column('person', sa.Enum('diogo', 'lis', name='person_type'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('match_type', sa.Enum('contains', 'starts_with', 'exact', name='match_type'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_category_budgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['savings_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'transfer', 'investment', name='tx_type'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('person', sa.Enum('diogo', 'lis', 'joint', name='person_tx'), nullable=False),
    sa.Column('source', sa.Enum('bank', 'credit_card', 'manual', name='tx_source'), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(length=200), nullable=True),
    sa.Column('raw_text', sa.String(length=500), nullable=True),
    sa.Column('manually_categorized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('plan_category_budgets')
    op.drop_table('category_rules')
    op.drop_table('uploaded_files')
    op.drop_table('savings_plans')
    op.drop_table('categories')
    # ### end Alembic commands ###
